DROP TABLE IF EXISTS #__pvoks_acrediteds;
DROP TABLE IF EXISTS #__pvoks_categories; 
DROP TABLE IF EXISTS #__pvoks_configs; 
DROP TABLE IF EXISTS #__pvoks_logs; 
DROP TABLE IF EXISTS #__pvoks_members;
DROP TABLE IF EXISTS #__pvoks_options;
DROP TABLE IF EXISTS #__pvoks_questions;
DROP TABLE IF EXISTS #__pvoks_supports;
DROP TABLE IF EXISTS #__pvoks_voters;
DROP TABLE IF EXISTS #__pvoks_votes;
DROP TRIGGER IF EXISTS `acredited_insert_log`;
DROP TRIGGER IF EXISTS `acredited_update_log` ;
DROP TRIGGER IF EXISTS `acredited_delete_log` ;
DROP TRIGGER IF EXISTS `category_insert_log` ;
DROP TRIGGER IF EXISTS `category_update_log` ;
DROP TRIGGER IF EXISTS `category_delete_log` ;
DROP TRIGGER IF EXISTS `config_insert_log` ;
DROP TRIGGER IF EXISTS `config_update_log` ;
DROP TRIGGER IF EXISTS `config_delete_log` ;
DROP TRIGGER IF EXISTS `member_insert_log` ;
DROP TRIGGER IF EXISTS `member_update_log` ;
DROP TRIGGER IF EXISTS `member_delete_log` ;
DROP TRIGGER IF EXISTS  `option_insert_log` ;
DROP TRIGGER IF EXISTS `option_update_log` ;
DROP TRIGGER IF EXISTS `option_delete_log` ;
DROP TRIGGER IF EXISTS `question_insert_log` ;
DROP TRIGGER IF EXISTS `question_update_log` ;
DROP TRIGGER IF EXISTS  `question_delete_log` ;
DROP TRIGGER IF EXISTS `support_insert_log` ;
DROP TRIGGER IF EXISTS `support_update_log` ;
DROP TRIGGER IF EXISTS `support_delete_log` ;
DROP TRIGGER IF EXISTS `voter_insert_log` ;
DROP TRIGGER IF EXISTS `voter_update_log` ;
DROP TRIGGER IF EXISTS `voter_delete_log` ;
DROP TRIGGER IF EXISTS vote_insert_log` ;
DROP TRIGGER IF EXISTS  `vote_update_log` ;
DROP TRIGGER IF EXISTS `vote_delete_log` ;

